/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gmplib_gmpjni_GMP_MutableInteger */

#ifndef _Included_org_gmplib_gmpjni_GMP_MutableInteger
#define _Included_org_gmplib_gmpjni_GMP_MutableInteger
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
