/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gmplib_gmpjni_GMP_mpz_t */

#ifndef _Included_org_gmplib_gmpjni_GMP_mpz_t
#define _Included_org_gmplib_gmpjni_GMP_mpz_t
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gmplib_gmpjni_GMP_mpz_t
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_00024mpz_1t_init
  (JNIEnv *, jobject);

/*
 * Class:     org_gmplib_gmpjni_GMP_mpz_t
 * Method:    init2
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_00024mpz_1t_init2
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP_mpz_t
 * Method:    fini
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_00024mpz_1t_fini
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
