/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gmplib_gmpjni_GMP */

#ifndef _Included_org_gmplib_gmpjni_GMP
#define _Included_org_gmplib_gmpjni_GMP
#ifdef __cplusplus
extern "C" {
#endif
#undef org_gmplib_gmpjni_GMP_MAX_UINT
#define org_gmplib_gmpjni_GMP_MAX_UINT 4294967295i64
#undef org_gmplib_gmpjni_GMP_UINT_MAX
#define org_gmplib_gmpjni_GMP_UINT_MAX 4294967295i64
#undef org_gmplib_gmpjni_GMP_ULONG_MAX
#define org_gmplib_gmpjni_GMP_ULONG_MAX 4294967295i64
#undef org_gmplib_gmpjni_GMP_LONG_MAX
#define org_gmplib_gmpjni_GMP_LONG_MAX 2147483647L
#undef org_gmplib_gmpjni_GMP_GMP_LIMB_BITS
#define org_gmplib_gmpjni_GMP_GMP_LIMB_BITS 32L
#undef org_gmplib_gmpjni_GMP_GMP_NAIL_BITS
#define org_gmplib_gmpjni_GMP_GMP_NAIL_BITS 0L
#undef org_gmplib_gmpjni_GMP_GMP_NUMB_BITS
#define org_gmplib_gmpjni_GMP_GMP_NUMB_BITS 32L
/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_set_str
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1set_1str
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_get_str
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1get_1str
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_set_str
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1set_1str
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_get_str
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1get_1str
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_set_str
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1set_1str
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_gmp_version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_gmplib_gmpjni_GMP_native_1gmp_1version
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_get_d_2exp
 * Signature: (Lorg/gmplib/gmpjni/GMP/MutableInteger;J)D
 */
JNIEXPORT jdouble JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1get_1d_12exp
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_get_d_2exp
 * Signature: (Lorg/gmplib/gmpjni/GMP/MutableInteger;J)D
 */
JNIEXPORT jdouble JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1get_1d_12exp
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_get_str
 * Signature: (Lorg/gmplib/gmpjni/GMP/MutableInteger;IJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1get_1str
  (JNIEnv *, jclass, jobject, jint, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_out_str
 * Signature: (Ljava/lang/String;IJ)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1out_1str
  (JNIEnv *, jclass, jstring, jint, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_inp_str
 * Signature: (JLjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1inp_1str
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_out_str
 * Signature: (Ljava/lang/String;IJ)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1out_1str
  (JNIEnv *, jclass, jstring, jint, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_inp_str
 * Signature: (JLjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1inp_1str
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_out_str
 * Signature: (Ljava/lang/String;IJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1out_1str
  (JNIEnv *, jclass, jstring, jint, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_inp_str
 * Signature: (JLjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1inp_1str
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_refmpn_cmp
 * Signature: (J[JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1refmpn_1cmp
  (JNIEnv *, jclass, jlong, jlongArray, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_set
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1set
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_set_ui
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1set_1ui
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_set_si
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1set_1si
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_set_d
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1set_1d
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_set_q
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1set_1q
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_set_f
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1set_1f
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_swap
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1swap
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_get_ui
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1get_1ui
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_get_si
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1get_1si
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_get_d
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1get_1d
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_add
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1add
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_add_ui
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1add_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_sub
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1sub
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_sub_ui
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1sub_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_ui_sub
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1ui_1sub
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_mul
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1mul
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_mul_si
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1mul_1si
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_mul_ui
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1mul_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_addmul
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1addmul
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_addmul_ui
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1addmul_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_submul
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1submul
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_submul_ui
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1submul_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_mul_2exp
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1mul_12exp
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_neg
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1neg
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_abs
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1abs
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_cdiv_q
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1cdiv_1q
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_cdiv_r
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1cdiv_1r
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_cdiv_qr
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1cdiv_1qr
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_cdiv_q_ui
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1cdiv_1q_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_cdiv_r_ui
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1cdiv_1r_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_cdiv_qr_ui
 * Signature: (JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1cdiv_1qr_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_cdiv_ui
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1cdiv_1ui
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_cdiv_q_2exp
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1cdiv_1q_12exp
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_cdiv_r_2exp
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1cdiv_1r_12exp
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_fdiv_q
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1fdiv_1q
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_fdiv_r
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1fdiv_1r
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_fdiv_qr
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1fdiv_1qr
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_fdiv_q_ui
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1fdiv_1q_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_fdiv_r_ui
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1fdiv_1r_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_fdiv_qr_ui
 * Signature: (JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1fdiv_1qr_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_fdiv_ui
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1fdiv_1ui
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_fdiv_q_2exp
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1fdiv_1q_12exp
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_fdiv_r_2exp
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1fdiv_1r_12exp
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_tdiv_q
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1tdiv_1q
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_tdiv_r
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1tdiv_1r
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_tdiv_qr
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1tdiv_1qr
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_tdiv_q_ui
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1tdiv_1q_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_tdiv_r_ui
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1tdiv_1r_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_tdiv_qr_ui
 * Signature: (JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1tdiv_1qr_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_tdiv_ui
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1tdiv_1ui
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_tdiv_q_2exp
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1tdiv_1q_12exp
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_tdiv_r_2exp
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1tdiv_1r_12exp
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_mod
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1mod
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_mod_ui
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1mod_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_divexact
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1divexact
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_divexact_ui
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1divexact_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_divisible_p
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1divisible_1p
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_divisible_ui_p
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1divisible_1ui_1p
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_divisible_2exp_p
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1divisible_12exp_1p
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_congruent_p
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1congruent_1p
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_congruent_ui_p
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1congruent_1ui_1p
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_congruent_2exp_p
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1congruent_12exp_1p
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_powm
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1powm
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_powm_ui
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1powm_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_powm_sec
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1powm_1sec
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_pow_ui
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1pow_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_ui_pow_ui
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1ui_1pow_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_root
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1root
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_rootrem
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1rootrem
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_sqrt
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1sqrt
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_sqrtrem
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1sqrtrem
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_perfect_power_p
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1perfect_1power_1p
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_perfect_square_p
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1perfect_1square_1p
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_probab_prime_p
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1probab_1prime_1p
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_nextprime
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1nextprime
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_gcd
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1gcd
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_gcd_ui
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1gcd_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_gcdext
 * Signature: (JJJJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1gcdext
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_lcm
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1lcm
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_lcm_ui
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1lcm_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_invert
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1invert
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_jacobi
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1jacobi
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_legendre
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1legendre
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_kronecker
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1kronecker
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_kronecker_si
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1kronecker_1si
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_kronecker_ui
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1kronecker_1ui
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_si_kronecker
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1si_1kronecker
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_ui_kronecker
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1ui_1kronecker
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_remove
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1remove
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_fac_ui
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1fac_1ui
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_2fac_ui
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_12fac_1ui
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_mfac_uiui
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1mfac_1uiui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_primorial_ui
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1primorial_1ui
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_bin_ui
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1bin_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_bin_uiui
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1bin_1uiui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_fib_ui
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1fib_1ui
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_fib2_ui
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1fib2_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_lucnum_ui
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1lucnum_1ui
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_lucnum2_ui
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1lucnum2_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_cmp
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1cmp
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_cmp_d
 * Signature: (JD)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1cmp_1d
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_cmp_si
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1cmp_1si
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_cmp_ui
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1cmp_1ui
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_cmpabs
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1cmpabs
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_cmpabs_d
 * Signature: (JD)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1cmpabs_1d
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_cmpabs_ui
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1cmpabs_1ui
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_sgn
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1sgn
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_and
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1and
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_ior
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1ior
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_xor
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1xor
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_com
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1com
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_popcount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1popcount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_hamdist
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1hamdist
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_scan0
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1scan0
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_scan1
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1scan1
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_setbit
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1setbit
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_clrbit
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1clrbit
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_combit
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1combit
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_tstbit
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1tstbit
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_fits_ulong_p
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1fits_1ulong_1p
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_fits_slong_p
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1fits_1slong_1p
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_fits_uint_p
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1fits_1uint_1p
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_fits_sint_p
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1fits_1sint_1p
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_fits_ushort_p
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1fits_1ushort_1p
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_fits_sshort_p
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1fits_1sshort_1p
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_odd_p
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1odd_1p
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_even_p
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1even_1p
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_sizeinbase
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1sizeinbase
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_getlimbn
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1getlimbn
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_canonicalize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1canonicalize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_set
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1set
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_set_z
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1set_1z
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_set_ui
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1set_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_set_si
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1set_1si
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_swap
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1swap
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_get_d
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1get_1d
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_set_d
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1set_1d
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_set_f
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1set_1f
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_add
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1add
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_sub
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1sub
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_mul
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1mul
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_mul_2exp
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1mul_12exp
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_div
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1div
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_div_2exp
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1div_12exp
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_neg
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1neg
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_abs
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1abs
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_inv
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1inv
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_cmp
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1cmp
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_cmp_ui
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1cmp_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_cmp_si
 * Signature: (JIJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1cmp_1si
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_cmp_z
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1cmp_1z
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_sgn
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1sgn
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_equal
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1equal
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_get_num
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1get_1num
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_get_den
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1get_1den
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_set_num
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1set_1num
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_set_den
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1set_1den
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_set_default_prec
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1set_1default_1prec
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_get_default_prec
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1get_1default_1prec
  (JNIEnv *, jclass);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_get_prec
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1get_1prec
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_set_prec
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1set_1prec
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_set_prec_raw
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1set_1prec_1raw
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_set
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1set
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_set_ui
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1set_1ui
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_set_si
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1set_1si
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_set_d
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1set_1d
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_set_z
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1set_1z
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_set_q
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1set_1q
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_swap
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1swap
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_get_d
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1get_1d
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_get_si
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1get_1si
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_get_ui
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1get_1ui
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_add
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1add
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_add_ui
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1add_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_sub
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1sub
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_ui_sub
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1ui_1sub
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_sub_ui
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1sub_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_mul
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1mul
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_mul_ui
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1mul_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_div
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1div
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_ui_div
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1ui_1div
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_div_ui
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1div_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_sqrt
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1sqrt
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_sqrt_ui
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1sqrt_1ui
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_pow_ui
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1pow_1ui
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_neg
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1neg
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_abs
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1abs
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_mul_2exp
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1mul_12exp
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_div_2exp
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1div_12exp
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_cmp
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1cmp
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_cmp_d
 * Signature: (JD)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1cmp_1d
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_cmp_ui
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1cmp_1ui
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_cmp_si
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1cmp_1si
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_eq
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1eq
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_reldiff
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1reldiff
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_sgn
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1sgn
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_ceil
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1ceil
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_floor
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1floor
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_trunc
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1trunc
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_integer_p
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1integer_1p
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_fits_ulong_p
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1fits_1ulong_1p
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_fits_slong_p
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1fits_1slong_1p
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_fits_uint_p
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1fits_1uint_1p
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_fits_sint_p
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1fits_1sint_1p
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_fits_ushort_p
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1fits_1ushort_1p
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpf_fits_sshort_p
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpf_1fits_1sshort_1p
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_gmp_urandomb_ui
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1gmp_1urandomb_1ui
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_gmp_urandomm_ui
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1gmp_1urandomm_1ui
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_urandomb
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1urandomb
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_urandomm
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1urandomm
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_rrandomb
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1rrandomb
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_internal_SIZ
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1internal_1SIZ
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_internal_SETSIZ
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1internal_1SETSIZ
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_internal_ABSIZ
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1internal_1ABSIZ
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_internal_ALLOC
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1internal_1ALLOC
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_internal_REALLOC
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1internal_1REALLOC
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_internal_CHECK_FORMAT
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1internal_1CHECK_1FORMAT
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpq_internal_CHECK_FORMAT
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpq_1internal_1CHECK_1FORMAT
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_internal_get_ulimb
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1internal_1get_1ulimb
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gmplib_gmpjni_GMP
 * Method:    native_mpz_internal_set_ulimb
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_org_gmplib_gmpjni_GMP_native_1mpz_1internal_1set_1ulimb
  (JNIEnv *, jclass, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
